# Generated by Django 3.0.7 on 2020-09-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='To-Do Description'),
        ),
    ]
