# Generated by Django 3.0.7 on 2020-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200929_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
