# Generated by Django 3.0.7 on 2020-10-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200930_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional: Type this if only you want this todo to expire', null=True),
        ),
    ]
