# Generated by Django 3.0.7 on 2020-10-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_todo_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, help_text='Optional: Only use this when you have completed your todo!', null=True, verbose_name='Completed Todo'),
        ),
    ]
